# roles/consul/tasks/download.yml
---
- name: download | remote archive
  get_url:
    url: "{{ consul.remote_archive }}"
    dest: "{{ consul.local_archive }}"
    checksum: "{{ consul.download_checksum }}"
    mode: 0644
    force: no
  when: consul.remote_archive | match("^http.*$")
  tags:
    - download

- name: download | local copy
  copy:
    src: "{{ consul.remote_archive }}"
    dest: "{{ consul.local_archive }}"
  when: consul.remote_archive | match("^(?!http).*$")

- name: download | unpack archive
  unarchive:
    src: "{{ consul.local_archive }}"
    dest: "{{ base_script_dir }}"
    copy: no
    creates: "{{ base_script_dir }}/consul"

#- block:
#  - name: download | remote ui archive
#    get_url:
#      url: "{{ consul.webui.remote_archive }}"
#      dest: "{{ consul.webui.local_archive }}"
#      checksum: "{{ consul.webui.download_checksum }}"
#      mode: 0644
#      force: no
#    when: consul.webui.remote_archive | match("^http.*$")
#    tags:
#      - download
#
#  - name: download | local ui copy
#    copy:
#      src: "{{ consul.webui.remote_archive }}"
#      dest: "{{ consul.webui.local_archive }}"
#    when: consul.webui.remote_archive | match("^(?!http).*$")
#
#  - name: download | unpack ui archive
#    unarchive:
#      src: "{{ consul.webui.local_archive }}"
#      dest: "{{ consul.home_dir }}"
#      copy: no
#      creates: "{{ consul.home_dir }}/index.html"
#  when: consul_webui_enabled
